### ISSUE TITLE
Be able to avvoid certain nodes when finding neighbors and paths

### ISSUE THREAD

**Issue by EspenMarthini** [bergos/rdf-path#1]
I have a proposal for changing the following files: neighbors.js and shortest.js

Create a blacklist of nodes as additional parameter.

See: https://github.com/EspenMarthini/rdf-path-dev

**Comment by bergos** [comment]
Thanks! I will merge it if you create a pull request.

[Grapoi](https://github.com/rdf-ext/grapoi) is the successor of this library but currently comes without shortest-path algorithms. Maybe still worth having a look if you are working on traversing related algorithms.

P.S. I'm on vacation and may not have time to process the PR in the next three weeks. But will check when I'm back!

**Comment by bergos** [comment]
Sorry for the delay. Just merged #2 and released v0.1.1.
